version: '3.8'

services:
  backend:
    build: ./backend
    container_name: sdg-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/__pycache__
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    container_name: sdg-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend