services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    ports: [ "8000:8000" ]
    volumes:
      - ./backend:/app
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: npm run dev
    ports: 
    - "3000:3000"
    environment:
      - NEXT_PUBLIC_FASTAPI_BASE=http://backend:8000
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules         # anonymous volume so node_modules stays Linux-native
